apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spire-voice.fullname" . }}-data
  labels:
    {{- include "spire-voice.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spire-voice.fullname" . }}-models
  labels:
    {{- include "spire-voice.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
  {{- if .Values.persistence.models.storageClassName }}
  storageClassName: {{ .Values.persistence.models.storageClassName }}
  {{- end }}
